export declare const getNames: (o: any) => string[];
export declare const warn: {
    (...data: any[]): void;
    (message?: any, ...optionalParams: any[]): void;
};
export declare const err2: {
    (...data: any[]): void;
    (message?: any, ...optionalParams: any[]): void;
};
export declare const err: (msg: string, value?: any) => void;
export declare const progress: (msg: string, value?: any) => void;
export declare const joy: (msg: string, value?: any) => void;
export declare const success: (msg: string, value?: any) => void;
export declare const log: (msg: string, value?: any) => void;
export declare const log1: (msg: string, value?: any) => void;
export declare const log2: (msg: string, value?: any) => void;
export declare const log3: (msg: string, value?: any) => void;
export declare const log4: (msg: string, value?: any) => void;
export declare const log5: (msg: string, value?: any) => void;
export declare const log6: (msg: string, value?: any) => void;
export declare const log7: (msg: string, value?: any) => void;
export declare const enter: (msg: string, value?: any) => void;
export declare const enter0: (msg: string, value?: any) => void;
export declare const enter1: (msg: string, value?: any) => void;
export declare const enter2: (msg: string, value?: any) => void;
export declare const enter3: (msg: string, value?: any) => void;
export declare const enter4: (msg: string, value?: any) => void;
export declare const enter5: (msg: string, value?: any) => void;
export declare const enter6: (msg: string, value?: any) => void;
export declare const enter7: (msg: string, value?: any) => void;
export declare const exit: (msg: string, value?: any) => void;
export declare const start: (msg: string, value?: any) => void;
export declare const fini: (msg: string, value?: any) => void;
export declare const pause: (msg: string, value?: any) => void;
export declare const resume: (msg: string, value?: any) => void;
export declare const bar: (msg?: string, value?: any) => void;
export declare const greybar: (msg?: string, value?: any) => void;
export declare const whitebar: (msg?: string, value?: any) => void;
export declare const bluebar: (msg?: string, value?: any) => void;
export declare const redbar: (msg?: string, value?: any) => void;
export declare const greenbar: (msg?: string, value?: any) => void;
export declare const orangebar: (msg?: string, value?: any) => void;
export declare const pass: (msg: string, value?: any) => void;
export declare const fail: (msg: string, value?: any) => void;
export declare const exe: (msg: string, value?: any) => void;
export declare const exe1: (msg: string, value?: any) => void;
export declare const exe2: (msg: string, value?: any) => void;
export declare const exe3: (msg: string, value?: any) => void;
export declare const exe4: (msg: string, value?: any) => void;
export declare const exe5: (msg: string, value?: any) => void;
export declare const exe6: (msg: string, value?: any) => void;
export declare const exe7: (msg: string, value?: any) => void;
