declare const _default: {
    getNames(o: any): string[];
    log(msg: string, value?: any): void;
    log1(msg: string, value?: any): void;
    log2(msg: string, value?: any): void;
    log3(msg: string, value?: any): void;
    log4(msg: string, value?: any): void;
    log5(msg: string, value?: any): void;
    log6(msg: string, value?: any): void;
    log7(msg: string, value?: any): void;
    enter(msg: string, value?: any): void;
    enter0(msg: string, value?: any): void;
    enter1(msg: string, value?: any): void;
    enter2(msg: string, value?: any): void;
    enter3(msg: string, value?: any): void;
    enter4(msg: string, value?: any): void;
    enter5(msg: string, value?: any): void;
    enter6(msg: string, value?: any): void;
    enter7(msg: string, value?: any): void;
    exit(msg: string, value?: any): void;
    start(msg: string, value?: any): void;
    fini(msg: string, value?: any): void;
    pause(msg: string, value?: any): void;
    resume(msg: string, value?: any): void;
    bar(msg?: string, value?: any): void;
    greybar(msg?: string, value?: any): void;
    bluebar(msg?: string, value?: any): void;
    redbar(msg?: string, value?: any): void;
    whitebar(msg?: string, value?: any): void;
    greenbar(msg?: string, value?: any): void;
    orangebar(msg?: string, value?: any): void;
    pass(msg: string, value?: any): void;
    fail(msg: string, value?: any): void;
    exe(msg: string, value?: any): void;
    exe1(msg: string, value?: any): void;
    exe2(msg: string, value?: any): void;
    exe3(msg: string, value?: any): void;
    exe4(msg: string, value?: any): void;
    exe5(msg: string, value?: any): void;
    exe6(msg: string, value?: any): void;
    exe7(msg: string, value?: any): void;
};
export default _default;
